test_add_decimal_numbers (tests.test_calculator.TestCalculator) ... FAIL
test_add_mixed_numbers (tests.test_calculator.TestCalculator) ... FAIL
test_add_negative_numbers (tests.test_calculator.TestCalculator) ... FAIL
test_add_positive_numbers (tests.test_calculator.TestCalculator) ... FAIL
test_add_zeros (tests.test_calculator.TestCalculator) ... FAIL

======================================================================
FAIL: test_add_decimal_numbers (tests.test_calculator.TestCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvasiljevic/continue/projects/projects/replay2/replay_output/test0/83/code/tests/test_calculator.py", line 23, in test_add_decimal_numbers
    self.assertEqual(add_numbers(1.5, 2.5), 4.0)
AssertionError: 5.0 != 4.0

======================================================================
FAIL: test_add_mixed_numbers (tests.test_calculator.TestCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvasiljevic/continue/projects/projects/replay2/replay_output/test0/83/code/tests/test_calculator.py", line 17, in test_add_mixed_numbers
    self.assertEqual(add_numbers(-2, 5), 3)
AssertionError: 4 != 3

======================================================================
FAIL: test_add_negative_numbers (tests.test_calculator.TestCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvasiljevic/continue/projects/projects/replay2/replay_output/test0/83/code/tests/test_calculator.py", line 14, in test_add_negative_numbers
    self.assertEqual(add_numbers(-2, -3), -5)
AssertionError: -4 != -5

======================================================================
FAIL: test_add_positive_numbers (tests.test_calculator.TestCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvasiljevic/continue/projects/projects/replay2/replay_output/test0/83/code/tests/test_calculator.py", line 11, in test_add_positive_numbers
    self.assertEqual(add_numbers(2, 3), 5)
AssertionError: 6 != 5

======================================================================
FAIL: test_add_zeros (tests.test_calculator.TestCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvasiljevic/continue/projects/projects/replay2/replay_output/test0/83/code/tests/test_calculator.py", line 20, in test_add_zeros
    self.assertEqual(add_numbers(0, 0), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
