test_add_mixed_numbers (tests.test_calculator.TestCalculator) ... FAIL
test_add_negative_numbers (tests.test_calculator.TestCalculator) ... FAIL
test_add_positive_numbers (tests.test_calculator.TestCalculator) ... FAIL
test_add_zero (tests.test_calculator.TestCalculator) ... FAIL

======================================================================
FAIL: test_add_mixed_numbers (tests.test_calculator.TestCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvasiljevic/continue/projects/projects/replay2/replay_output/test0/85/code/tests/test_calculator.py", line 22, in test_add_mixed_numbers
    self.assertEqual(add_numbers(-2, 5), 3)
AssertionError: 4 != 3

======================================================================
FAIL: test_add_negative_numbers (tests.test_calculator.TestCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvasiljevic/continue/projects/projects/replay2/replay_output/test0/85/code/tests/test_calculator.py", line 18, in test_add_negative_numbers
    self.assertEqual(add_numbers(-2, -3), -5)
AssertionError: -4 != -5

======================================================================
FAIL: test_add_positive_numbers (tests.test_calculator.TestCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvasiljevic/continue/projects/projects/replay2/replay_output/test0/85/code/tests/test_calculator.py", line 14, in test_add_positive_numbers
    self.assertEqual(add_numbers(2, 3), 5)
AssertionError: 6 != 5

======================================================================
FAIL: test_add_zero (tests.test_calculator.TestCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvasiljevic/continue/projects/projects/replay2/replay_output/test0/85/code/tests/test_calculator.py", line 26, in test_add_zero
    self.assertEqual(add_numbers(0, 0), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 4 tests in 0.000s

FAILED (failures=4)
